AWSTemplateFormatVersion: '2010-09-09'
Description: 'Week 6-1: 간단한 S3 버킷 스택 - CloudFormation 기본 개념 학습'

Parameters:
  BucketPrefix:
    Type: String
    Default: cloudformation-lab
    Description: S3 버킷 이름 접두사
    AllowedPattern: ^[a-z0-9-]*$
    ConstraintDescription: 소문자, 숫자, 하이픈만 사용 가능합니다

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketPrefix}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: 생성된 S3 버킷 이름
    Value: !Ref MyS3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: S3 버킷 ARN
    Value: !GetAtt MyS3Bucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
