AWSTemplateFormatVersion: '2010-09-09'
Description: 'Week 2-2: IAM Role and AssumeRole Lab - Pre-built Environment (lab-user + Access Key + S3 Bucket)'

# AWS CloudFormation 템플릿: AWS Identity and Access Management 역할 및 AssumeRole 실습을 위한 테스트 환경
# 이 템플릿은 lab-user AWS Identity and Access Management 사용자, Access Key, 테스트용 Amazon S3 버킷을 자동으로 생성합니다.
# 학생들은 AWS Identity and Access Management 역할 생성 및 AssumeRole API 호출에 집중할 수 있습니다.

Parameters:
  EnvironmentName:
    Type: String
    Default: 'week2-2-iam-role'
    Description: Environment name (used for resource naming)
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Only lowercase letters, numbers, and hyphens are allowed

  ProjectTag:
    Type: String
    Default: 'AWS-Lab'
    Description: Project tag value

  WeekTag:
    Type: String
    Default: '2-2'
    Description: Week tag value

  CreatedByTag:
    Type: String
    Default: 'CloudFormation'
    Description: CreatedBy tag value

Resources:
  # AWS Identity and Access Management 사용자: lab-user (AssumeRole 테스트용)
  LabUser:
    Type: AWS::IAM::User
    Properties:
      UserName: lab-user
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # Access Key: lab-user용 (AWS Command Line Interface/API 테스트용)
  LabUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref LabUser

  # Amazon S3 버킷: 역할 권한 테스트용
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'iam-role-lab-${AWS::AccountId}'
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

Outputs:
  LabUserName:
    Description: IAM user name (used in Task 4 for AssumeRole permission)
    Value: !Ref LabUser
    Export:
      Name: !Sub '${EnvironmentName}-LabUserName'

  LabUserAccessKeyId:
    Description: Access Key ID (used for AWS CLI configuration)
    Value: !Ref LabUserAccessKey
    Export:
      Name: !Sub '${EnvironmentName}-AccessKeyId'

  LabUserSecretAccessKey:
    Description: Secret Access Key (used for AWS CLI configuration)
    Value: !GetAtt LabUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${EnvironmentName}-SecretAccessKey'

  TestBucketName:
    Description: Test S3 bucket name (used in Task 5-6 for permission testing)
    Value: !Ref TestBucket
    Export:
      Name: !Sub '${EnvironmentName}-TestBucketName'

  TestBucketArn:
    Description: Test S3 bucket ARN
    Value: !GetAtt TestBucket.Arn
    Export:
      Name: !Sub '${EnvironmentName}-TestBucketArn'
