AWSTemplateFormatVersion: '2010-09-09'
Description: 'Week 2-2: AWS Identity and Access Management 역할 및 AssumeRole 실습 - 사전 환경 구축 (lab-user + Access Key + Amazon S3 버킷)'

# AWS CloudFormation 템플릿: AWS Identity and Access Management 역할 및 AssumeRole 실습을 위한 테스트 환경
# 이 템플릿은 lab-user AWS Identity and Access Management 사용자, Access Key, 테스트용 Amazon S3 버킷을 자동으로 생성합니다.
# 학생들은 AWS Identity and Access Management 역할 생성 및 AssumeRole API 호출에 집중할 수 있습니다.

Parameters:
  EnvironmentName:
    Type: String
    Default: 'week2-2-iam-role'
    Description: 환경 이름 (리소스 명명에 사용)
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: 소문자, 숫자, 하이픈만 사용 가능

  ProjectTag:
    Type: String
    Default: 'AWS-Lab'
    Description: Project 태그 값

  WeekTag:
    Type: String
    Default: '2-2'
    Description: Week 태그 값

  CreatedByTag:
    Type: String
    Default: 'CloudFormation'
    Description: CreatedBy 태그 값

Resources:
  # AWS Identity and Access Management 사용자: lab-user (AssumeRole 테스트용)
  LabUser:
    Type: AWS::IAM::User
    Properties:
      UserName: lab-user
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # Access Key: lab-user용 (AWS Command Line Interface/API 테스트용)
  LabUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref LabUser

  # Amazon S3 버킷: 역할 권한 테스트용
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'iam-role-lab-${AWS::AccountId}'
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

Outputs:
  LabUserName:
    Description: AWS Identity and Access Management 사용자 이름 (태스크 4에서 AssumeRole 권한 부여 시 사용)
    Value: !Ref LabUser
    Export:
      Name: !Sub '${EnvironmentName}-LabUserName'

  LabUserAccessKeyId:
    Description: Access Key ID (AWS Command Line Interface 설정 시 사용)
    Value: !Ref LabUserAccessKey
    Export:
      Name: !Sub '${EnvironmentName}-AccessKeyId'

  LabUserSecretAccessKey:
    Description: Secret Access Key (AWS Command Line Interface 설정 시 사용)
    Value: !GetAtt LabUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${EnvironmentName}-SecretAccessKey'

  TestBucketName:
    Description: 테스트용 Amazon Simple Storage Service 버킷 이름 (태스크 5-6에서 권한 테스트 시 사용)
    Value: !Ref TestBucket
    Export:
      Name: !Sub '${EnvironmentName}-TestBucketName'

  TestBucketArn:
    Description: 테스트용 Amazon Simple Storage Service 버킷 ARN
    Value: !GetAtt TestBucket.Arn
    Export:
      Name: !Sub '${EnvironmentName}-TestBucketArn'
