AWSTemplateFormatVersion: '2010-09-09'
Description: 'Week 5-1: Amazon RDS Multi-AZ Lab Environment - VPC, Subnets, Security Groups, DB Subnet Group Auto-Creation'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'week5-1-rds'
    Description: Environment name (used for resource tagging)
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Only lowercase letters, numbers, and hyphens allowed

  ProjectTag:
    Type: String
    Default: 'AWS-Lab'
    Description: Project tag value

  WeekTag:
    Type: String
    Default: '5-1'
    Description: Week tag value

  CreatedByTag:
    Type: String
    Default: 'CloudFormation'
    Description: CreatedBy tag value

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-VPC'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-IGW'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnets (NAT Gateway용)
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Public-Subnet-A'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Public-Subnet-C'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # Private Subnets (RDS용)
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Private-Subnet-A'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.12.0/24
      AvailabilityZone: !Select [2, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Private-Subnet-C'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # NAT Gateway (Private 서브넷의 아웃바운드 인터넷 연결용)
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NAT-EIP'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NAT-Gateway'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Public-RT'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable

  # Private Route Table
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Private-RT'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetC
      RouteTableId: !Ref PrivateRouteTable

  # RDS Security Group
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${EnvironmentName}-RDS-SG'
      GroupDescription: Security group for RDS MySQL instance
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16
          Description: Allow MySQL from VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-RDS-SG'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${EnvironmentName}-db-subnet-group'
      DBSubnetGroupDescription: Subnet group for RDS instances
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-db-subnet-group'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # EC2 Security Group (MySQL 클라이언트용, 선택사항)
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${EnvironmentName}-EC2-SG'
      GroupDescription: Security group for EC2 MySQL client
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-EC2-SG'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Lab
          Value: 'Week5-1'
        - Key: Purpose
          Value: 'RDS Multi-AZ Lab'
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Week
          Value: !Ref WeekTag
        - Key: CreatedBy
          Value: !Ref CreatedByTag

  # RDS Security Group에 EC2에서의 접근 허용
  RDSSecurityGroupIngressFromEC2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RDSSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref EC2SecurityGroup
      Description: Allow MySQL from EC2 instances

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'

  PublicSubnetAId:
    Description: Public Subnet A ID
    Value: !Ref PublicSubnetA
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnetA'

  PublicSubnetCId:
    Description: Public Subnet C ID
    Value: !Ref PublicSubnetC
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnetC'

  PrivateSubnetAId:
    Description: Private Subnet A ID (ap-northeast-2a)
    Value: !Ref PrivateSubnetA
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnetA'

  PrivateSubnetCId:
    Description: Private Subnet C ID (ap-northeast-2c)
    Value: !Ref PrivateSubnetC
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnetC'

  DBSubnetGroupName:
    Description: DB Subnet Group Name
    Value: !Ref DBSubnetGroup
    Export:
      Name: !Sub '${AWS::StackName}-DBSubnetGroup'

  RDSSecurityGroupId:
    Description: RDS Security Group ID
    Value: !Ref RDSSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-RDSSecurityGroup'

  EC2SecurityGroupId:
    Description: EC2 Security Group ID (for MySQL client)
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-EC2SecurityGroup'

  NATGatewayId:
    Description: NAT Gateway ID
    Value: !Ref NATGateway

  NATGatewayEIP:
    Description: NAT Gateway Elastic IP
    Value: !Ref NATGatewayEIP
