AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple S3 bucket template for learning CloudFormation basics'

Parameters:
  BucketNamePrefix:
    Description: Prefix for S3 bucket name (will be appended with account ID)
    Type: String
    Default: my-cfn-bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketNamePrefix}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Lab
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
    
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt MyS3Bucket.Arn
