AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket with new name - This will cause replacement'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'new-bucket-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Demo
        - Key: Purpose
          Value: ChangeSetDemo

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
